export const PERMISSIONS = {
  // Product
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",

  // Category
  CATEGORY_CREATE: "CATEGORY_CREATE",
  CATEGORY_VIEW: "CATEGORY_VIEW",
  CATEGORY_UPDATE: "CATEGORY_UPDATE",
  CATEGORY_DELETE: "CATEGORY_DELETE",

  // Brand
  BRAND_CREATE: "BRAND_CREATE",
  BRAND_VIEW: "BRAND_VIEW",
  BRAND_UPDATE: "BRAND_UPDATE",
  BRAND_DELETE: "BRAND_DELETE",

  // Orders
  ORDER_CREATE: "ORDER_CREATE",
  ORDER_VIEW: "ORDER_VIEW",
  ORDER_UPDATE: "ORDER_UPDATE",
  ORDER_DELETE: "ORDER_DELETE",

  // Users
  USER_CREATE: "USER_CREATE",
  USER_VIEW: "USER_VIEW",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",

  // Vendors
  VENDOR_CREATE: "VENDOR_CREATE",
  VENDOR_VIEW: "VENDOR_VIEW",
  VENDOR_UPDATE: "VENDOR_UPDATE",
  VENDOR_DELETE: "VENDOR_DELETE",

  // Dashboard
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  // Settings
  SETTINGS_VIEW: "SETTINGS_VIEW",
  SETTINGS_UPDATE: "SETTINGS_UPDATE"
};