import { ROLES } from "./roles.js";
import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
  // Super Admin gets every permission automatically
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  // Admin Permissions
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,

    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.CATEGORY_VIEW,
    PERMISSIONS.CATEGORY_UPDATE,
    PERMISSIONS.CATEGORY_DELETE,

    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.ORDER_DELETE,

    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_UPDATE,

    PERMISSIONS.VENDOR_VIEW,
    PERMISSIONS.VENDOR_UPDATE,

    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_UPDATE,
  ],

  // Vendor Permissions
  [ROLES.VENDOR]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_UPDATE,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_UPDATE,
  ],

  // Employee Permissions
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PRODUCT_VIEW,

    PERMISSIONS.CATEGORY_VIEW,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_UPDATE,
  ],

  // Customer Permissions
  [ROLES.CUSTOMER]: [
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_VIEW,
  ],
};